### ISSUE TITLE
Redis probes list issues - Multi-instance API problems

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#120]
This is a task to track the issue where sometimes an API instance shows a partial list of the connected probes.
It has happened in the simple CLI script and production API as well.

Need to verify that our API is 100% stable when running multiple instances with a central Redis DB.

**Comment by jimaek** [comment]
Waiting for redis adapter bug fix

**Comment by patrykcieszkowski** [comment]
heres the problem:
- server A manages X probes
- server B manages Y probes
- the load balancer redirects user to A or B
- at random, server A or B wouldnt respond to probe list query (pub/sub)

**Comment by alexey-yarmosh** [comment]
Hey @patrykcieszkowski, I am trying to address that issue and Dmitriy told me that you had a script to get a list of probes from the specific node instance/process. Could you share it please? If you don't mind.

Also, if you have any info on how the issue can be steadily reproduced, that would be very helpful. Thanks!

**Comment by patrykcieszkowski** [comment]
I don't recall writing such a script, but it should be as simple as adding a node identifier k/v to the probe data.

https://github.com/jsdelivr/globalping/blob/master/src/probe/builder.ts#L90-L105
https://github.com/jsdelivr/globalping/blob/master/src/probe/route/get-probes.ts#L16-L33

I also never figured out how to consistently replicate that issue. In fact, it never happened on my local network, even while running over 500 probes. One thing is for certain - even when connecting to the WS pool externally, and pulling the probe list while bypassing the HTTP server, the behaviour mentioned in the comment above was present. I came to the conclusion that some nodes would either never receive the pub requesting the data, or wouldn't respond to it on time (redis-adapter has a timeout).

**Comment by alexey-yarmosh** [comment]
I was constantly requesting /probes endpoint from both APIs and what I am observing is:
- under usual load diff between responses may be ~1-2 probes, because some probes are constantly reconnecting (IP limit). Current fetchSockets adapter firstly gets local probes, then asks to get remote ones. While awaiting for remote, some local probes may disconnect, but we already got the list - that is why unsync happens.
- under the high load, redis operations (and pub/sub that adapter is using) takes more time + there are more porbes reconnecting, that is why diff may be ~1-10 probes.
- also, under the load there is issue #234 in that case 500 http error is returned.
- also, under the load sometimes both APIs simultaneously respond only with their own probes.

As I see, the only thing we can do here is to try another adapter implementation and compare the behaviour. For some teams AMPQ adapter showed [really good results](https://piotr-frankowski.medium.com/socket-io-adapters-and-their-performance-issue-cabee346b7bd).

**Comment by alexey-yarmosh** [comment]
AMPQ adapter does not support some of the operation (e.g. [fetchSockets()](https://github.com/sensibill/socket.io-amqp/issues/18)).
I've also tried [NATS adapter](https://github.com/distrue/socket.io-nats-adapter), but fetchSockets there also works not as expected.
