### ISSUE TITLE
City names containing hyphens won't match via magic field

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping#167]
Because we use `-` as a replacement for ` ` in magic matching. These names seem to be quite common, particularly in Asia. I think we can solve this by replacing `-` with whitespace in our internal normalization step and consider the two equivalent in our matching.

**Comment by MartinKolarik** [comment]
Right now for magic, we replace `-` with whitespace in the user query. Unless I missed something, that means cities that actually have `-` in their name, won't match.

**Comment by patrykcieszkowski** [comment]
`magic` relies on a pre-mapped index, where we replace all dashes with whitespaces.
https://github.com/jsdelivr/globalping/blob/master/src/probe/builder.ts#L87

We then do the same for user-input, to match the index:
https://github.com/jsdelivr/globalping/blob/master/src/probe/router.ts#L16

We could use dashes instead of whitespaces, but that doesn't really make any difference at the end of the day.

**Comment by MartinKolarik** [comment]
Ok I missed the builder part here.
