### ISSUE TITLE
unresolvable geoip

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#255]
5.161.143.28 (my own server)

```
[2022-12-12 16:06:23] [INFO] [685] [general] Start probe version 0.10.1 in a production mode
[2022-12-12 16:06:23] [ERROR] [685] [general] connection to API failed: unresolvable geoip
```

Why unresolvable? Isn't our logic to fallback to ipinfo? In which case it would be marked as Washington https://ipinfo.io/5.161.143.28
Digitalelement resolves it as well, only maxmind doesnt. So why in case of 2 successful resolutions we fail?

**Comment by jimaek** [comment]
That is wrong, we probably need to add a fake state "D.C." and assign probes to it. Because the "Washington" state is on the other side of the country. @MartinKolarik agreed?

**Comment by MartinKolarik** [comment]
We have the state, except it is known under two names, see:
 - https://github.com/jsdelivr/globalping/blob/master/src/lib/location/states.ts#L12
 - https://en.wikipedia.org/wiki/Washington,_D.C..

We should swap the keys and values in the states object so that multiple names can map to the same code (makes more sense considering [we use it as a lookup from names to codes](https://github.com/jsdelivr/globalping/blob/f9e56fb7ba4e13bd66b543d5d94dc2032463c850/src/lib/location/location.ts#L35) too) and add a mapping from "Washington, D.C." to "DC".
