### ISSUE TITLE
Set up and implement E2E tests

### ISSUE THREAD

**Issue by alexey-yarmosh** [jsdelivr/globalping#281]
We need to create E2E tests, so we will be able to test the integration between globalping and globalping-probe. Then we will be able to run these tests as a part of github checks in both repos.

Sample steps may look like these:
- download latest globalping sources
- build and run globalping as a docker container
- download and run latest globalping-probe image with globalping container as a host
- run E2E tests (e.g. REST measeurement request with the result validation)

**Comment by MartinKolarik** [comment]
The way I expect this to work:

 - A new test suite is added either here or in the probe repo:
   - It waits till the API reports a probe is connected, then runs at least one measurement of each type and does basic checks on the responses (could be more since one measurement type may have multiple response schemas depending on the request parameters; see docs). 
   - All responses are also verified using `matchApiSchema()` (see existing usage in this repo).
 - A new GitHub action is added here, which starts the API, clones the probe repo, configures the probe to connect to the API, and runs the tests.
 - Similar action can then be used in the probe repo as well.

**Comment by alexey-yarmosh** [comment]
Solution should has scenarios of:
- GET probes
- POST measurement
- GET measurement
- measurement timeout
- adopted probes data sync

**Comment by MartinKolarik** [comment]
@jimaek I think we already had a custom runner for some project?

**Comment by alexey-yarmosh** [comment]
Works 👍
