### ISSUE TITLE
Reduce the number of progress messages

### ISSUE THREAD

**Issue by alexey-yarmosh** [jsdelivr/globalping#308]
If user makes a request to 500 probes he can hardly look at the progress of all of them at once. Proposed rule is for all measurements with NofProbes > 10 to receive real-time updates from first 10 probes, and other 490 will send only the result.

This could be implemented inside the ack handler that triggers the probe to start the measurement. We can send `liveUpdate: true` as the ack body from API to probe to first 10 probes. That way probes that first triggered the ack request will be live, plus that probes will be always at the beginning of the `results` array.

**Comment by jimaek** [comment]
Sounds reasonable. This way the web tools and CLI can still render the real-time tests on top to make it look good.

**Comment by MartinKolarik** [comment]
This should be combined with the other idea. Let the user specify how many probes he wants real-time updates from and change rate limits so that a test with real-time updates counts us two.

The actual default (10 max) could even be let to the individual tools, and the API could default to no real-time at all. If the tool doesn't actually have its own logic for quickly polling the results, it won't see the updates anyway, and if it does, it knows best how many results it can reasonably display.

**Comment by jimaek** [comment]
>This should be combined with the other idea. Let the user specify how many probes he wants real-time updates from and change rate limits so that a test with real-time updates counts us two.

I disagree, maximum we should allow a true/false option for real-time overall and then promise a best effort. With real-time=true as default. This way if the tool doesnt need it at all it can specify it. But per probe makes no sense to me.

And then if real-time is enabled we use the value we decide, 10 sounds reasonable for now.

**Comment by MartinKolarik** [comment]
Updated version after discussion:

We introduce a new option, `inProgressUpdates` (final name TBD in the PR), which defaults to `false` so by default, there are no in-progress updates at all. Our own tools (and anyone else's if they want) will set the option to `true` though, and with `true`, we'll process updates as we do now but only for the first 5 probes (this limit won't be user-configurable).
