### ISSUE TITLE
Possible abuse happening right now

### ISSUE THREAD

**Issue by MarvinJWendt** [jsdelivr/globalping#464]
Hi there. I noticed that my probe received a lot of requests overnight (1.4k). Out of curiosity, I queried the IDs through the API. A lot of requests seem to be for `*.microcharon.com`. 

The subdomain seems to be a random ID, **maybe to prevent rate limiting?** (which would be abuse)

Just a short snippet of my logs:

| Request ID | Target |
|------------|--------|
| 7S1lWpvTU8Qv7oRy | SYxckhvtgf.microcharon.com |
| uvGLCQs6y6o2AhHv | a5breT3PnT.microcharon.com |
| QIssYinalvEq7Syd | 7JcDL4QRR5.microcharon.com |
| TkPOQMezw5BGfeHW | TubBFcPcJU.microcharon.com |
| KulnTz5NeFvAy3sK | 2SRBV7X3SS.microcharon.com |
| kIwAynN21sbzrzYq | W6cqy0ZHV3.microcharon.com |
| HHLVCuVaK5cWEzMX | irwjXTphQK.microcharon.com |
| Uxdddj62muUvlc56 | tSSuMZuESg.microcharon.com |
| 1h62oFtYSsucn2b4 | EXRRIO1HY0.microcharon.com |
| 3Je6pDWyvomGLpas | efp7oDj49y.microcharon.com |
| 6sqvmmKVQU5d87Dj | MJ04Tuab9V.microcharon.com |
| nn2EOMFsZKzhBAQ5 | Yu0TZCwRVT.microcharon.com |
| HtDJ9MBZfdCfwUsI | AsR4Fota7Z.microcharon.com |
| VXXQOFBrfBQkQpGn | Yfh7zPs7NT.microcharon.com |
| kEOOmPY6vyLlYB7i | Zd3FuuMc9n.microcharon.com |
| tdTtn9ZGVptnkLHq | ed7YxytRue.microcharon.com |
| xVtpddgu6EF0zetq | QG9ZgGiCpD.microcharon.com |
| frh56HJZs53CJ7i7 | zZcOlIm2a6.microcharon.com |
| kHB6ncIuChzpIJxx | DTdLvRY04a.microcharon.com |
| bmCXIdzDe3HzGsPb | pEv9skCmnf.microcharon.com |

**Comment by jimaek** [comment]
It seems they are using random subdomains to bypass DNS caches and test the latency of their DNS service directly. 
Doesn't seem malicious at all but they do run more tests that needed.

I believe for now this is ok, it's actually useful to stress test our systems as we plan to do upgrades and improve the overall performance. We want to handle millions of measurements and thousands of probes eventually.

We keep our limits very high at the moment since we don't have API keys yet, but once our dashboard goes live, probably in the next 2 months, this user will automatically get rate-limited according to the new limits.

Thanks for reporting this! :)

**Comment by MarvinJWendt** [comment]
Thanks for looking into this! Using a random ID to bypass the DNS cache is something that I didn't think of, but it makes sense!

Happy holidays! 🎄
